[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoSliderServer = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4"

[compat]
Literate = ">=0.2.7"
Pluto = ">=0.17.4"